// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Talkable.Data.Entities;
using Talkable.Data.Models;

#nullable disable

namespace Talkable.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20260216134400_CreateSignsTable")]
    partial class CreateSignsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Talkable.Data.Models.CourseFeedback", b =>
                {
                    b.Property<int>("Feedback_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Feedback_Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Course_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("DateTime");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Feedback_Id");

                    b.HasIndex("Course_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Tb_CourseFeedback");
                });

            modelBuilder.Entity("Talkable.Data.Models.Courses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<string>("Instructor_Info")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("Tb_Courses");
                });

            modelBuilder.Entity("Talkable.Data.Models.Signs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnimationPath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("Tb_Signs");
                });

            modelBuilder.Entity("Talkable.Data.Models.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DateTime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("User_Id");

                    b.ToTable("Tb_Users");
                });

            modelBuilder.Entity("Talkable.Data.Models.UserCourses", b =>
                {
                    b.Property<int>("UserCourses_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserCourses_Id"));

                    b.Property<int>("Completed_Lessons")
                        .HasColumnType("int");

                    b.Property<int>("Course_Id")
                        .HasColumnType("int");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("UserCourses_Id");

                    b.HasIndex("Course_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Tb_UserCourses");
                });

            modelBuilder.Entity("Talkable.Data.Models.CourseFeedback", b =>
                {
                    b.HasOne("Talkable.Data.Models.Courses", "Courses")
                        .WithMany("User_Feedback")
                        .HasForeignKey("Course_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talkable.Data.Models.User", "user")
                        .WithMany("User_Feedback")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Talkable.Data.Models.UserCourses", b =>
                {
                    b.HasOne("Talkable.Data.Models.Courses", "Tbcourse")
                        .WithMany("User_courses")
                        .HasForeignKey("Course_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talkable.Data.Models.User", "Tbuser")
                        .WithMany("User_Courses")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tbcourse");

                    b.Navigation("Tbuser");
                });

            modelBuilder.Entity("Talkable.Data.Models.Courses", b =>
                {
                    b.Navigation("User_Feedback");

                    b.Navigation("User_courses");
                });

            modelBuilder.Entity("Talkable.Data.Models.User", b =>
                {
                    b.Navigation("User_Courses");

                    b.Navigation("User_Feedback");
                });
#pragma warning restore 612, 618
        }
    }
}
